server:
  port: 8810
  servlet:
    context-path: /api

# Spring conf
spring:
  application:
    name: file-storage
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


app:
  azure-account:
    name:
    key:
  offsetHours: 24
